services:
  web:
    build:
      context: ./www
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: incidencias
      MYSQL_USER: usuari
      MYSQL_PASSWORD: usuari1234
      LANG: C.UTF-8
    volumes:
      - ./db_data:/var/lib/mysql
      - ./db_init:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    ports:
      - "8081:8080"
    depends_on:
      - db
